#!/bin/bash

sudo pkill -f "bin/rails s -b 0.0.0.0 -e production -p 9191 -d"

sudo python3 /usr/lib/raspiwifi/reset_device/reset.py &

sudo python3 /usr/lib/raspiwifi/reset_device/connection_monitor.py &
