#!/bin/bash

python3 /usr/lib/raspiwifi/reset_device/reset.py &

python3 /usr/lib/raspiwifi/configuration_app/app.py &

hostapd -dd /etc/hostapd/hostapd.conf &

# Set outing tables to redirect all http requests to the locally running COnfiguration Server
sudo iptables -t nat -A PREROUTING -d 0/0 -p tcp --dport 80 -j DNAT --to-destination 10.0.0.1:9191
